
用python的faker生成模拟数据发送到kafka中出现超时的错误，求解

我是用虚拟机去做的，搭了一个单机kafka测试，一直链接不上
 server的配置也改过了，网上的教程看了个遍 没啥用，求解~~~

